spring.application.name=order-service

server.port=8083

spring.datasource.url=jdbc:postgresql://ecommerce-db:5432/ecommerce_project

spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka


resilience4j.circuitbreaker.instances.productService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.productService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.productService.sliding-window-size=10
resilience4j.circuitbreaker.instances.productService.wait-duration-in-open-state=10s
